### ISSUE TITLE
How would I put the four datasets in for training?

### ISSUE THREAD

**Issue by 750928465** [EmmaW8/Dofe#5]

**Comment by 750928465** [comment]
Should I put all four datasets in one folder at once, or should I put them in separate folders and specify the paths?
Thank you for answering.

**Comment by 750928465** [comment]
Is it enough to put the four dataset folders in the location specified by agrs.data_dir?

**Comment by emma-sjwang** [comment]
separately

**Comment by emma-sjwang** [comment]
https://github.com/emma-sjwang/Dofe/blob/d3a1d35f2c01679fdf5feeee9f315baf61180029/dataloaders/fundus_dataloader.py#L48C23-L48C23

**Comment by 750928465** [comment]
Thank you so much for the repost!
